language: objective-c
osx_image: xcode9.2
gemfile: Gemfile

branches:
  only:
    - master # Build all executables for Production
    - develop # Build all executables for Development + Testing
    - apps/catatan-muslim-app/main

cache:
  - cocoapods
  - carthage

before_install:
  - bash scripts/setup.sh

notifications:
 email:
  - m.muizzsuddin@gmail.com

jobs:
  include:
    - name: Production
      if: branch = master
      script: scrips/ci/production.sh
    
    - name: Development
      if: branch = develop
      env: TEST=true
      script: bash scripts/ci/development.sh

    - name: Muslim App Release
      if: branch = apps/muslim_app/main
      script: bash scripts/ci/muslim_app.sh

    - name: Catatan Muslim App Release
      if: branch = apps/catatan-muslim-app/main
      script: bash scripts/ci/catatan_muslim_app.sh
    - name: Catatan Muslim App Testing
      if: branch = apps/catatan-muslim-app/main
      env: TEST=true
      script: bash scripts/ci/catatan_muslim_app.sh