language: objective-c
osx_image: xcode9.2
cache:
 - cocoapods
 - carthage

before_install:
 - carthage bootstrap --cache-builds --platform iOS
 - pod install

notifications:
 email:
  - m.muizzsuddin@gmail.com

script:
  - xcodebuild -workspace MuslimAppWorkspace.xcworkspace -scheme MuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 
  - xcodebuild -workspace MuslimAppWorkspace.xcworkspace -scheme CatatanMuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

