language: objective-c
osx_image: xcode9.2
gemfile: Gemfile

branches:
  only:
    - master
    - develop
    - apps/catatan-muslim-app/main

cache:
  - cocoapods
  - carthage

before_install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install
  - carthage bootstrap --cache-builds --platform iOS

notifications:
 email:
  - m.muizzsuddin@gmail.com

jobs:
  include:
    - name: Development Release
      if: branch = develop
      script: bash scripts/ci/muslim_app.sh

    - name: Catatan Muslim App Release
      if: branch = apps/catatan-muslim-app/main
      script: bash scripts/ci/catatan_muslim_app.sh
    - name: Catatan Muslim App Testing
      if: branch = apps/catatan-muslim-app/main
      env: TEST=true
      script: bash scripts/ci/catatan_muslim_app.sh