language: objective-c
osx_image: xcode9.2
cache:
 - cocoapods
 - carthage

before_install:
 - bundle install
 - bundle exec pod repo update
 - bundle exec pod install
 - carthage bootstrap --cache-builds --platform iOS

notifications:
 email:
  - m.muizzsuddin@gmail.com

script:
  # TESTING
    # BUILD
    - xcodebuild -workspace MuslimAppWorkspace.xcworkspace -scheme MuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Debug build-for-testing
      #- xcodebuild -workspace MuslimAppWorkspace.xcworkspace -scheme CatatanMuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Debug build-for-testing
    # TEST
    - xctool -workspace MuslimAppWorkspace.xcworkspace -scheme MuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Debug run-tests
      #- xctool -workspace MuslimAppWorkspace.xcworkspace -scheme CatatanMuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Debug run-tests
  
  # PRODUCTION
  - xcodebuild -workspace MuslimAppWorkspace.xcworkspace -scheme MuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Release
    #- xcodebuild -workspace MuslimAppWorkspace.xcworkspace -scheme CatatanMuslimApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Release
